AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  IndexLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos-new
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos
      Description: 'Lambda function for CD'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::419065928887:role/service-role/index-photos-role-1n4x2x5c'
      Environment:
        Variables:
          REGION: us-east-1
  SearchLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos-new
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos
      Description: 'Lambda function for CD'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::419065928887:role/service-role/search_photo-role-ykvxluok'
      Environment:
        Variables:
          REGION: us-east-1
            
           